// live-sim-template-version: 2
/**
 * ============================================================================
 * live-sim Reverse Proxy Auth Gate (gate.cjs)
 * ============================================================================
 *
 * Purpose:
 * serve-sim captures the simulator and exposes port 3200 locally without built-in
 * authentication. Exposing port 3200 directly through a public tunnel would allow
 * anyone with the URL to control your iOS simulator.
 *
 * This zero-dependency Node.js reverse proxy:
 * 1. Requires a secret access token via query string `?k=<token>` upon first access.
 * 2. Exchanges the query parameter for a secure `HttpOnly` session cookie.
 * 3. Proxies all HTTP requests (including MJPEG video stream chunks) to serve-sim.
 * 4. Multiplexes and pipes WebSocket upgrade connections for real-time touch input.
 * ============================================================================
 */

const http = require('node:http');
const net = require('node:net');

// Configuration loaded from environment variables
const TOKEN = process.env.LIVE_SIM_GATE_TOKEN || '';
const TARGET_PORT = Number(process.env.LIVE_SIM_TARGET_PORT || 3200);
const TARGET_HOST = '127.0.0.1';
const PORT = Number(process.env.LIVE_SIM_GATE_PORT || 3199);
const COOKIE_NAME = 'live_sim_k';

// Security check: Refuse to start without an authentication secret
if (!TOKEN) {
  console.error('[ERROR] LIVE_SIM_GATE_TOKEN is required. Refusing to start unauthenticated proxy.');
  process.exit(1);
}

/**
 * Constant-time string comparison to prevent timing attacks.
 */
function timingSafeEqual(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string' || a.length !== b.length) {
    return false;
  }
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

/**
 * Extract the authentication cookie token from the request headers.
 */
function extractCookieToken(req) {
  const rawCookie = req.headers.cookie || '';
  const parts = rawCookie.split(';');
  for (const part of parts) {
    const [name, ...rest] = part.trim().split('=');
    if (name === COOKIE_NAME) {
      return decodeURIComponent(rest.join('='));
    }
  }
  return null;
}

/**
 * Validate incoming request authorization against cookie or query string token.
 */
function authorize(req) {
  // Check cookie authentication
  const cookieVal = extractCookieToken(req);
  if (cookieVal && timingSafeEqual(cookieVal, TOKEN)) {
    return 'cookie';
  }

  // Check URL query parameter authentication (?k=token)
  try {
    const parsedUrl = new URL(req.url, 'http://localhost');
    const queryVal = parsedUrl.searchParams.get('k');
    if (queryVal && timingSafeEqual(queryVal, TOKEN)) {
      return 'query';
    }
  } catch {}

  // Check Bearer authorization header
  const authHeader = req.headers.authorization || '';
  if (authHeader.startsWith('Bearer ') && timingSafeEqual(authHeader.slice(7).trim(), TOKEN)) {
    return 'bearer';
  }

  return false;
}

// Access denied HTML response template
const ACCESS_DENIED_HTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>live-sim · Access Denied</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 15vh auto; max-width: 32rem; padding: 0 1.5rem; color: #1f2328; background: #f6f8fa; line-height: 1.6; }
    .card { background: #ffffff; border: 1px solid #d0d7de; border-radius: 8px; padding: 2rem; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }
    h1 { font-size: 1.25rem; margin-top: 0; color: #cf222e; }
    code { background: #f6f8fa; padding: 0.2em 0.4em; border-radius: 4px; font-size: 0.9em; border: 1px solid #d0d7de; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Access Denied</h1>
    <p>This live iOS Simulator stream requires a valid access key.</p>
    <p>Please open the complete link with <code>?k=&lt;token&gt;</code> generated by your local <code>live-sim</code> CLI.</p>
  </div>
</body>
</html>`;

// Create HTTP Reverse Proxy Server
const server = http.createServer((req, res) => {
  // Health check endpoint used by the runner hold loop
  if (req.url === '/__live-sim/healthz') {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.end('ok');
    return;
  }

  const authMethod = authorize(req);
  if (!authMethod) {
    res.writeHead(403, { 'Content-Type': 'text/html; charset=utf-8' });
    res.end(ACCESS_DENIED_HTML);
    return;
  }

  // Preserve and normalize headers for serve-sim
  const headers = { ...req.headers };
  headers['host'] = `${TARGET_HOST}:${TARGET_PORT}`;
  headers['x-forwarded-host'] = req.headers['host'] || '';
  headers['x-forwarded-proto'] = 'https';

  // If authenticated via query string, strip token from internal target path
  let targetPath = req.url;
  if (authMethod === 'query') {
    try {
      const url = new URL(req.url, 'http://localhost');
      url.searchParams.delete('k');
      targetPath = url.pathname + (url.search ? url.search : '');
    } catch {}
  }

  // Pipe request to serve-sim
  const proxyReq = http.request(
    {
      hostname: TARGET_HOST,
      port: TARGET_PORT,
      path: targetPath,
      method: req.method,
      headers,
    },
    (proxyRes) => {
      const resHeaders = { ...proxyRes.headers };

      // Set cookie on query-based authentication
      if (authMethod === 'query') {
        const setCookie = `${COOKIE_NAME}=${encodeURIComponent(TOKEN)}; Path=/; HttpOnly; SameSite=Lax; Secure`;
        resHeaders['set-cookie'] = resHeaders['set-cookie']
          ? [].concat(resHeaders['set-cookie'], setCookie)
          : [setCookie];
      }

      res.writeHead(proxyRes.statusCode, resHeaders);
      proxyRes.pipe(res);
    }
  );

  proxyReq.on('error', (err) => {
    res.writeHead(502, { 'Content-Type': 'text/plain' });
    res.end(`Proxy Gateway Error: ${err.message}`);
  });

  req.pipe(proxyReq);
});

// Handle WebSocket Upgrades (Transmits browser touch/swipe events to simulator)
server.on('upgrade', (req, socket, head) => {
  if (!authorize(req)) {
    socket.write('HTTP/1.1 403 Forbidden\r\n\r\n');
    socket.destroy();
    return;
  }

  const targetSocket = net.connect(TARGET_PORT, TARGET_HOST, () => {
    const rawHeaders = Object.entries(req.headers)
      .map(([k, v]) => {
        if (k.toLowerCase() === 'host') return `host: ${TARGET_HOST}:${TARGET_PORT}`;
        return `${k}: ${v}`;
      })
      .join('\r\n');
    targetSocket.write(`${req.method} ${req.url} HTTP/${req.httpVersion}\r\n${rawHeaders}\r\n\r\n`);
    if (head && head.length) targetSocket.write(head);
    targetSocket.pipe(socket);
    socket.pipe(targetSocket);
  });

  targetSocket.on('error', () => socket.destroy());
  socket.on('error', () => targetSocket.destroy());
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`[live-sim gate] Listening on 127.0.0.1:${PORT} -> 127.0.0.1:${TARGET_PORT}`);
});
